name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ShipFast-Syndicate/.github/.github/workflows/reusable-release.yml@78bee37c6546003297a5740bbbc16a29f0832480 # v1
    secrets: inherit
