// Snapshot of Better Auth 1.7.5 plus enterprise plugin models.
// The schema drift test compares this contract to getAuthTables().
export const EXPECTED_TABLES: Record<string, string[]> = {
  user: [
    "id",
    "name",
    "email",
    "emailVerified",
    "image",
    "createdAt",
    "updatedAt",
    "role",
    "banned",
    "banReason",
    "banExpires",
    "twoFactorEnabled",
    "studio_ref",
  ],
  organization: ["id", "name", "slug", "logo", "createdAt", "metadata", "studio_ref"],
  team: ["id", "name", "memberCount", "organizationId", "createdAt", "updatedAt"],
  teamMember: ["id", "teamId", "userId", "membershipKey", "createdAt"],
  member: ["id", "organizationId", "userId", "role", "createdAt"],
  invitation: [
    "id",
    "organizationId",
    "email",
    "role",
    "teamId",
    "status",
    "expiresAt",
    "createdAt",
    "inviterId",
  ],
  twoFactor: [
    "id",
    "secret",
    "backupCodes",
    "userId",
    "verified",
    "failedVerificationCount",
    "lockedUntil",
  ],
  passkey: [
    "id",
    "name",
    "publicKey",
    "userId",
    "credentialID",
    "counter",
    "deviceType",
    "backedUp",
    "transports",
    "createdAt",
    "aaguid",
  ],
  apikey: [
    "id",
    "configId",
    "name",
    "start",
    "referenceId",
    "prefix",
    "key",
    "refillInterval",
    "refillAmount",
    "lastRefillAt",
    "enabled",
    "rateLimitEnabled",
    "rateLimitTimeWindow",
    "rateLimitMax",
    "requestCount",
    "remaining",
    "lastRequest",
    "expiresAt",
    "createdAt",
    "updatedAt",
    "permissions",
    "metadata",
  ],
  ssoProvider: [
    "id",
    "issuer",
    "oidcConfig",
    "samlConfig",
    "userId",
    "providerId",
    "organizationId",
    "domain",
    "domainVerified",
  ],
  scimManagedConnection: [
    "id",
    "creationRequestId",
    "connectionId",
    "provisioningDomainId",
    "status",
    "revision",
    "createdAt",
    "createdBy",
    "decommissionStartedAt",
    "decommissionStartedBy",
    "decommissionedAt",
    "decommissionedBy",
  ],
  scimManagedCredential: [
    "id",
    "connectionRecordId",
    "credentialId",
    "tokenDigest",
    "hashVersion",
    "activeSlotKey",
    "status",
    "serializedScopes",
    "expiresAt",
    "createdAt",
    "createdBy",
    "lastUsedAt",
    "revokedAt",
    "revokedBy",
    "decommissionedAt",
  ],
  scimManagedConnectionEvent: [
    "id",
    "connectionRecordId",
    "eventKey",
    "sequence",
    "type",
    "actorId",
    "credentialId",
    "createdAt",
  ],
  scimConnectionBinding: [
    "id",
    "connectionId",
    "connectionKey",
    "provisioningDomainId",
    "createdAt",
    "decommissionedAt",
    "decommissionStatus",
    "decommissionCursorUserId",
    "decommissionReconciledUserCount",
    "decommissionBatchCount",
    "decommissionRevision",
    "decommissionCompletedAt",
    "decommissionLeaseId",
    "decommissionLeaseExpiresAt",
  ],
  scimIdentityTombstone: [
    "id",
    "connectionId",
    "provisioningDomainId",
    "externalId",
    "externalIdKey",
    "userId",
    "profile",
    "deletedAt",
  ],
  scimSubject: ["id", "userId", "profileSourceId", "revision", "createdAt", "updatedAt"],
  scimUser: [
    "id",
    "connectionId",
    "provisioningDomainId",
    "userId",
    "connectionUserKey",
    "userName",
    "userNameKey",
    "primaryEmail",
    "workEmailValueIndex",
    "emailValueIndex",
    "displayName",
    "formattedName",
    "givenName",
    "familyName",
    "serializedEmails",
    "serializedAttributes",
    "externalId",
    "externalIdKey",
    "active",
    "orderKey",
    "createdAt",
    "updatedAt",
  ],
  scimProjectionGrant: [
    "id",
    "connectionId",
    "provisioningDomainId",
    "scimUserId",
    "userId",
    "sourceKind",
    "sourceId",
    "sourceValue",
    "role",
    "grantKey",
    "createdAt",
    "updatedAt",
  ],
  scimGroup: [
    "id",
    "connectionId",
    "provisioningDomainId",
    "revision",
    "displayName",
    "displayNameKey",
    "externalId",
    "externalIdKey",
    "orderKey",
    "createdAt",
    "updatedAt",
  ],
  scimGroupMember: ["id", "connectionId", "groupId", "scimUserId", "membershipKey", "createdAt"],
  audit_event: [
    "id",
    "org_id",
    "seq",
    "actor_type",
    "actor_id",
    "action",
    "target_type",
    "target_id",
    "ip",
    "user_agent",
    "metadata",
    "created_at",
    "prev_hash",
    "hash",
  ],
  org_policy: [
    "id",
    "org_id",
    "require_2fa",
    "sso_enforced",
    "break_glass_user_id",
    "session_max_age_s",
    "allowed_methods",
    "group_role_map",
    "updated_at",
  ],
  enterprise_scim_member: ["id", "org_id", "user_id", "member_id", "last_role"],
};
